version: "3.0"

services:
  grafana:
    container_name: "correlation-matrix-panel"
    platform: "linux/amd64"
    build:
      context: "./.config"
      args:
        GRAFANA_IMAGE: ${GRAFANA_IMAGE}
        GRAFANA_VERSION: ${GRAFANA_VERSION}
        GRAFANA_PORT: ${GRAFANA_PORT}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - "./dist:/var/lib/grafana/plugins/correlation-matrix-panel"
      - "./provisioning:/etc/grafana/provisioning"
